export const builtinsData = [
  { name: "abs(x)", desc: "Returns the absolute value of a number." },
  { name: "all(iterable)", desc: "Returns True if all elements of the iterable are true." },
  { name: "any(iterable)", desc: "Returns True if any element of the iterable is true." },
  { name: "bin(x)", desc: "Converts an integer number to a binary string." },
  { name: "bool(x)", desc: "Converts a value to a Boolean." },
  { name: "dict(**kwarg)", desc: "Creates a new dictionary." },
  { name: "dir(object)", desc: "Without arguments, return the list of names in the current local scope. With an argument, attempt to return a list of valid attributes for that object." },
  { name: "divmod(a, b)", desc: "Takes two numbers as arguments and returns a pair of numbers consisting of their quotient and remainder." },
  { name: "enumerate(iterable, start=0)", desc: "Returns an enumerate object. iterable must be a sequence, an iterator, or some other object which supports iteration." },
  { name: "filter(function, iterable)", desc: "Constructs an iterator from those elements of iterable for which function returns true." },
  { name: "float(x)", desc: "Returns a floating point number constructed from a number or string x." },
  { name: "getattr(object, name[, default])", desc: "Returns the value of the named attribute of object." },
  { name: "hasattr(object, name)", desc: "Returns True if the string is the name of one of the object's attributes, False if not." },
  { name: "help([object])", desc: "Invokes the built-in help system." },
  { name: "hex(x)", desc: "Converts an integer number to a lowercase hexadecimal string prefixed with '0x'." },
  { name: "id(object)", desc: "Returns the 'identity' of an object (its memory address in CPython)." },
  { name: "int(x=0, base=10)", desc: "Returns an integer object constructed from a number or string x." },
  { name: "isinstance(object, classinfo)", desc: "Returns True if the object argument is an instance of the classinfo argument." },
  { name: "issubclass(class, classinfo)", desc: "Returns True if class is a subclass of classinfo." },
  { name: "len(s)", desc: "Returns the length (the number of items) of an object." },
  { name: "list([iterable])", desc: "Creates a new list." },
  { name: "map(function, iterable, ...)", desc: "Returns an iterator that applies function to every item of iterable, yielding the results." },
  { name: "max(iterable, *[, key, default])", desc: "Returns the largest item in an iterable or the largest of two or more arguments." },
  { name: "min(iterable, *[, key, default])", desc: "Returns the smallest item in an iterable or the smallest of two or more arguments." },
  { name: "next(iterator[, default])", desc: "Retrieves the next item from the iterator by calling its __next__() method." },
  { name: "pow(base, exp[, mod])", desc: "Returns base to the power exp." },
  { name: "print(*objects, sep=' ', end='\\n', file=sys.stdout, flush=False)", desc: "Prints objects to the text stream file, separated by sep and followed by end." },
  { name: "range(stop) / range(start, stop[, step])", desc: "Returns an immutable sequence of numbers from start to stop by step." },
  { name: "reversed(seq)", desc: "Returns a reverse iterator." },
  { name: "round(number[, ndigits])", desc: "Returns number rounded to ndigits precision after the decimal point." },
  { name: "set([iterable])", desc: "Returns a new set object, optionally with elements taken from iterable." },
  { name: "sorted(iterable, *, key=None, reverse=False)", desc: "Returns a new sorted list from the items in iterable." },
  { name: "str(object='')", desc: "Returns a str version of object." },
  { name: "sum(iterable, /, start=0)", desc: "Sums start and the items of an iterable from left to right and returns the total." },
  { name: "tuple([iterable])", desc: "Creates a new tuple." },
  { name: "type(object)", desc: "Returns the type of an object." },
  { name: "zip(*iterables, strict=False)", desc: "Iterates over several iterables in parallel, producing tuples with an item from each one." }
];
